import Vue from 'vue'
import { Button, Container, Header, Dropdown, DropdownMenu, DropdownItem, Menu, Submenu, Table, Aside, Main, TableColumn, MenuItem, Row, Col, Card, Input, Radio, DatePicker, RadioGroup, Dialog } from 'element-ui'

Vue.use(Button)
Vue.use(Container)
Vue.use(Header)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(Table)
Vue.use(Main)
Vue.use(Aside)
Vue.use(TableColumn)
Vue.use(MenuItem)
Vue.use(Row)
Vue.use(Col)
Vue.use(Card)
Vue.use(Input)
Vue.use(Radio)
Vue.use(DatePicker)
Vue.use(RadioGroup)
Vue.use(Dialog)
